# Generated by Django 5.0.6 on 2026-07-06 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='inactive', max_length=24)),
                ('provider', models.CharField(default='lemon_squeezy', max_length=40)),
                ('customer_id', models.CharField(blank=True, max_length=80)),
                ('subscription_id', models.CharField(blank=True, max_length=80)),
                ('order_id', models.CharField(blank=True, max_length=80)),
                ('product_id', models.CharField(blank=True, max_length=80)),
                ('variant_id', models.CharField(blank=True, max_length=80)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['subscription_id'], name='core_usersu_subscri_b2d648_idx'), models.Index(fields=['customer_id'], name='core_usersu_custome_8a466b_idx'), models.Index(fields=['status'], name='core_usersu_status_95365e_idx')],
            },
        ),
    ]
