# Generated by Django 5.0.6 on 2026-07-05 16:39

import django.db.models.deletion
import django.utils.timezone
import pricing.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pricing_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PricingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_audit_logs', to='pricing.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pricing.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_allowed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('competitor_median_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_gross_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_margin_percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('reason_code', models.CharField(max_length=80)),
                ('explanation', models.TextField()),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_recommendation_decisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_recommendations', to='pricing.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_recommendations', to='pricing.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorPriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=160)),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[pricing.validators.validate_positive_decimal])),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_price_snapshots', to='pricing.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_price_snapshots', to='pricing.product')),
            ],
            options={
                'ordering': ['-captured_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=3)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[pricing.validators.validate_positive_decimal])),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[pricing.validators.validate_positive_decimal])),
                ('minimum_margin_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[pricing.validators.validate_margin_percent])),
                ('stock_quantity', models.PositiveIntegerField(default=0, validators=[pricing.validators.validate_non_negative_int])),
                ('target_stock_quantity', models.PositiveIntegerField(default=0, validators=[pricing.validators.validate_non_negative_int])),
                ('is_pricing_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_profiles', to='pricing.organization')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_profile', to='pricing.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('units_sold', models.PositiveIntegerField(default=0, validators=[pricing.validators.validate_non_negative_int])),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[pricing.validators.validate_non_negative_decimal])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_snapshots', to='pricing.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_snapshots', to='pricing.product')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pricing.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('organization', 'sku'), name='unique_pricing_product_sku_per_org'),
        ),
    ]
