# Generated by Django 5.0.6 on 2026-07-09 22:07

import django.db.models.deletion
import django.utils.timezone
import pricing.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=120)),
                ('vat_mode', models.CharField(choices=[('included', 'VAT included'), ('excluded', 'VAT excluded'), ('exempt', 'VAT exempt')], default='included', max_length=24)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[pricing.validators.validate_non_negative_decimal])),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[pricing.validators.validate_non_negative_decimal])),
                ('update_limit', models.PositiveIntegerField(default=0, validators=[pricing.validators.validate_non_negative_int])),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['channel_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('segment', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('contract_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['segment', 'region'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=80)),
                ('assignment_ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('holdout_group', models.BooleanField(default=False)),
                ('reason_code', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-assignment_ts', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('holiday', 'Holiday'), ('fx', 'Foreign exchange'), ('weather', 'Weather'), ('season', 'Season'), ('inflation', 'Inflation'), ('campaign', 'Campaign'), ('other', 'Other')], max_length=24)),
                ('name', models.CharField(max_length=160)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('text_value', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observed_at', 'signal_type'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('promo_type', models.CharField(choices=[('percent', 'Percent discount'), ('amount', 'Fixed amount discount'), ('bundle', 'Bundle'), ('free_shipping', 'Free shipping'), ('other', 'Other')], default='amount', max_length=24)),
                ('discount_depth', models.DecimalField(decimal_places=2, max_digits=12, validators=[pricing.validators.validate_non_negative_decimal])),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('media_support', models.BooleanField(default=False)),
                ('media_support_note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_hand', models.PositiveIntegerField(default=0, validators=[pricing.validators.validate_non_negative_int])),
                ('reserved', models.PositiveIntegerField(default=0, validators=[pricing.validators.validate_non_negative_int])),
                ('lead_time_days', models.PositiveIntegerField(default=0, validators=[pricing.validators.validate_non_negative_int])),
                ('stockout_flag', models.BooleanField(default=False)),
                ('warehouse_id', models.CharField(blank=True, max_length=120)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-captured_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('qty', models.PositiveIntegerField(default=1, validators=[pricing.validators.validate_non_negative_int])),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[pricing.validators.validate_non_negative_decimal])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[pricing.validators.validate_non_negative_decimal])),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='competitorpricesnapshot',
            name='competitor_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='competitorpricesnapshot',
            name='crawl_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitorpricesnapshot',
            name='matched_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='competitorpricesnapshot',
            name='stock_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('in_stock', 'In stock'), ('out_of_stock', 'Out of stock'), ('limited', 'Limited')], default='unknown', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='lifecycle_stage',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('discontinued', 'Discontinued')], default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_class',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(blank=True, default='unit', max_length=40),
        ),
        migrations.AddField(
            model_name='productpricingprofile',
            name='cogs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[pricing.validators.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='productpricingprofile',
            name='landed_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[pricing.validators.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='productpricingprofile',
            name='map_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum advertised price.', max_digits=12, null=True, validators=[pricing.validators.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='productpricingprofile',
            name='msrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[pricing.validators.validate_non_negative_decimal]),
        ),
        migrations.AddField(
            model_name='productpricingprofile',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[pricing.validators.validate_non_negative_decimal]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('product_id', ''), _negated=True), fields=('organization', 'product_id'), name='unique_pricing_product_id_per_org'),
        ),
        migrations.AddField(
            model_name='channelmetadata',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_metadata', to='pricing.organization'),
        ),
        migrations.AddField(
            model_name='customeraccountsignal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_account_signals', to='pricing.organization'),
        ),
        migrations.AddField(
            model_name='experimentobservation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_observations', to='pricing.organization'),
        ),
        migrations.AddField(
            model_name='experimentobservation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_observations', to='pricing.product'),
        ),
        migrations.AddField(
            model_name='externalsignal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_signals', to='pricing.organization'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='pricing.organization'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='pricing.product'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='pricing.organization'),
        ),
        migrations.AddField(
            model_name='stocksnapshot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='pricing.product'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_records', to='pricing.organization'),
        ),
        migrations.AddField(
            model_name='transactionrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_records', to='pricing.product'),
        ),
        migrations.AddConstraint(
            model_name='channelmetadata',
            constraint=models.UniqueConstraint(fields=('organization', 'channel_name'), name='unique_pricing_channel_per_org'),
        ),
        migrations.AddIndex(
            model_name='experimentobservation',
            index=models.Index(fields=['organization', 'variant', 'assignment_ts'], name='pricing_exp_organiz_36dcda_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsignal',
            index=models.Index(fields=['organization', 'signal_type', 'observed_at'], name='pricing_ext_organiz_c7d64f_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(condition=models.Q(('promo_id', ''), _negated=True), fields=('organization', 'promo_id'), name='unique_pricing_promo_id_per_org'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['organization', 'warehouse_id', 'captured_at'], name='pricing_sto_organiz_e2e2da_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionrecord',
            index=models.Index(fields=['organization', 'sku', 'timestamp'], name='pricing_tra_organiz_e46897_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionrecord',
            index=models.Index(fields=['organization', 'channel', 'timestamp'], name='pricing_tra_organiz_0dbff2_idx'),
        ),
    ]
